version: '3.11'
services:
  fastapi:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  vuejs:
    build: ./frontend
#    ports:
#      - "8080:8080"
    restart: unless-stopped

#  nginx:
#    build: ./nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - fastapi
#      - vuejs
#    restart: unless-stopped